// frontends-mobile/react-native/TodoApp/App.tsx
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */

import React, {useState, useEffect} from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
  Alert,
  Platform,
} from 'react-native';
import axios from 'axios';

interface Todo {
  id: number;
  text: string;
}

// Use different base URLs for iOS and Android
const API_BASE_URL = Platform.select({
  ios: 'http://127.0.0.1:8001',
  android: 'http://10.0.2.2:8001',
  default: 'http://localhost:8001',
});

function App(): React.JSX.Element {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [newTodo, setNewTodo] = useState('');

  const fetchTodos = async () => {
    try {
      const response = await axios.get(`${API_BASE_URL}/todos/`);
      setTodos(response.data);
    } catch (error) {
      console.error('Error fetching todos:', error);
      Alert.alert('Error', 'Failed to fetch todos');
    }
  };

  const addTodo = async () => {
    if (!newTodo.trim()) {
      Alert.alert('Error', 'Please enter a task');
      return;
    }

    try {
      await axios.post(`${API_BASE_URL}/todos/`, {
        text: newTodo.trim(),
      });
      setNewTodo('');
      fetchTodos();
    } catch (error) {
      console.error('Error adding todo:', error);
      Alert.alert('Error', 'Failed to add todo');
    }
  };

  const removeTodo = async (id: number) => {
    try {
      await axios.delete(`${API_BASE_URL}/todos/${id}`);
      fetchTodos();
    } catch (error) {
      console.error('Error removing todo:', error);
      Alert.alert('Error', 'Failed to remove todo');
    }
  };

  useEffect(() => {
    fetchTodos();
  }, []);

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="dark-content" />
      <ScrollView contentInsetAdjustmentBehavior="automatic">
        <View style={styles.header}>
          <Text style={styles.title}>To Do List</Text>
        </View>

        <View style={styles.inputContainer}>
          <Text style={styles.label}>What needs to be done?</Text>
          <TextInput
            style={styles.input}
            value={newTodo}
            onChangeText={setNewTodo}
            placeholder="Enter a new task"
          />
          <TouchableOpacity style={styles.addButton} onPress={addTodo}>
            <Text style={styles.buttonText}>Add</Text>
          </TouchableOpacity>
        </View>

        <View style={styles.tasksContainer}>
          <Text style={styles.tasksTitle}>Tasks</Text>
          {todos.length === 0 ? (
            <Text style={styles.noTasks}>No tasks</Text>
          ) : (
            todos.map(todo => (
              <View key={todo.id} style={styles.todoItem}>
                <Text style={styles.todoText}>{todo.text}</Text>
                <TouchableOpacity
                  style={styles.removeButton}
                  onPress={() => removeTodo(todo.id)}>
                  <Text style={styles.buttonText}>Remove</Text>
                </TouchableOpacity>
              </View>
            ))
          )}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  header: {
    padding: 20,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#333333',
  },
  inputContainer: {
    padding: 20,
    backgroundColor: '#FFFFFF',
    marginTop: 10,
  },
  label: {
    fontSize: 16,
    marginBottom: 10,
    color: '#333333',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 5,
    padding: 10,
    marginBottom: 10,
    fontSize: 16,
  },
  addButton: {
    backgroundColor: '#007AFF',
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  tasksContainer: {
    padding: 20,
    backgroundColor: '#FFFFFF',
    marginTop: 10,
  },
  tasksTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    color: '#333333',
  },
  noTasks: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
    marginTop: 20,
  },
  todoItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  todoText: {
    fontSize: 16,
    color: '#333333',
    flex: 1,
  },
  removeButton: {
    backgroundColor: '#FF3B30',
    padding: 8,
    borderRadius: 5,
    marginLeft: 10,
  },
});

export default App;

// frontends-web/vue/src/App.vue
<template>
  <div class="container mt-5">
    <h1>To Do List</h1>
    
    <!-- Add Todo Form -->
    <div class="card mb-4">
      <div class="card-body">
        <label for="newTodo" class="form-label">What needs to be done?</label>
        <div class="input-group">
          <input
            type="text"
            class="form-control"
            id="newTodo"
            v-model="newTodoText"
            @keyup.enter="addTodo"
            placeholder="Enter a new task"
          >
          <button class="btn btn-primary" @click="addTodo">Add</button>
        </div>
      </div>
    </div>

    <!-- Todo List -->
    <h2>Tasks</h2>
    <div v-if="todos.length === 0" class="alert alert-info">
      No tasks
    </div>
    <div v-else class="list-group">
      <div v-for="todo in todos" :key="todo.id" class="list-group-item d-flex justify-content-between align-items-center">
        <span>{{ todo.text }}</span>
        <button class="btn btn-danger btn-sm" @click="removeTodo(todo.id)">Remove</button>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'App',
  data() {
    return {
      todos: [],
      newTodoText: ''
    }
  },
  methods: {
    async fetchTodos() {
      try {
        const response = await axios.get('http://localhost:8001/todos/');
        this.todos = response.data;
      } catch (error) {
        console.error('Error fetching todos:', error);
      }
    },
    async addTodo() {
      if (!this.newTodoText.trim()) return;
      
      try {
        await axios.post('http://localhost:8001/todos/', {
          text: this.newTodoText
        });
        this.newTodoText = '';
        await this.fetchTodos();
      } catch (error) {
        console.error('Error adding todo:', error);
      }
    },
    async removeTodo(id) {
      try {
        await axios.delete(`http://localhost:8001/todos/${id}`);
        await this.fetchTodos();
      } catch (error) {
        console.error('Error removing todo:', error);
      }
    }
  },
  mounted() {
    this.fetchTodos();
  }
}
</script>

<style>
@import 'bootstrap/dist/css/bootstrap.min.css';

.container {
  max-width: 800px;
}

.list-group-item {
  transition: background-color 0.2s;
}

.list-group-item:hover {
  background-color: #f8f9fa;
}

.btn-danger {
  transition: all 0.2s;
}

.btn-danger:hover {
  transform: scale(1.05);
}
</style>
